import * as dotenv from "dotenv";
import { Client } from "./client.js";
import installDependencies from "./dependencies.js";
import { IS_REPLIT } from "./env.js";
dotenv.config();
await installDependencies();
if (IS_REPLIT) import("./keepalive.js");
const client = new Client();
await client.load();
await client.start();
