name: josh

on: push

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  version: latest
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: latest
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Run check script
              run: pnpm check
